#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! test $GITHUB_ACTIONS && ! test $SKIP; then
  GIT_USER_EMAIL=$(git config --global user.email)
  GIT_USER_NAME=$(git config --global user.name)

  if ! test -d packages/neovim/ts-dist || git diff --staged --name-only | grep -q '^packages/tree-sitter-aeria'; then
    ./scripts/rebuild-ts-dist.sh
    env -i sh -c "$(cat <<EOF
cd packages/neovim
export HOME=$HOME
git config --global user.email "$GIT_USER_EMAIL"
git config --global user.name "$GIT_USER_NAME"
git add ts-dist
git commit -m 'feat: update ts-dist' || true
EOF
)"
  fi

fi

git add pnpm-lock.yaml

